include:
  - docker-compose.network.yml
  - protocols/rest/docker-compose.yml
  - protocols/jsonrpc/docker-compose.yml
  - protocols/grpc/docker-compose.yml
  - monitoring/docker-compose.yml
  # - protocols/kafka/docker-compose.yml
  # - protocols/rabbitmq/docker-compose.yml